module.exports.constant = {
    user_role: /^PREDATOR$|^JUNIOR$|^SOPHOMORE$|^FRESHMAN$/,
    inner_err: 'inner error',
    password_not_match: 'Password doesn\'t match',
    email_null: 'email doesn\'t existed',
    email_format_illegal: 'email format is wrong',
    email_password_required: 'email and password required',
    invalid_email_password: 'invalid email or password',
    userid_required: 'userid required',
    user_not_found: 'user_not_found',
    asset_name_required: 'assetname required',
    submit_success: 'submit_success',
    account_not_found: 'account_not_found',
    false: 'false',
    true: 'true',
    asset_flag: 'assets_',
    receive_mq_flag: 'receive_mq_',
    confirm_mq_flag: 'confirm_mq_',
    token_flag: 'token_',
    account_flag: 'Account',
    name_flag: '_name',
    get_address_balance_error: 'get_address_balance_error',
    get_txs_error: 'get_txs_error',
    balance_not_enough: 'balance_not_enough',
    receive_threshold_flag: '_receive_threshold',
    send_threshold_flag: '_send_threshold',
    inwallet_mq_flag: 'inwallet_mq_',
    send_mq_flag: 'send_mq_',
    sendmq_flag: 'SendMQ_',
    address_flag: '_address',
    decimal_flag: '_decimal',
    confirm_flag: '_confirm',
    vailable_flag: 'Available',
    frozen_flag: 'Frozen',
    user_risk_check_error: 'User risk check error',
    over_time: 'over time',
}