module.exports.mq = {
    host: '127.0.0.1',
    port: 6379,
    ns: 'rsmq',
    delet_success: 1,
    delet_msg_not_found: 0,
    no_data_sleep: 1000 * 2,
    on_submit_ttl: 3 * 60 * 60 * 1000,
    on_receive_ttl: 3 * 60 * 60 * 1000,
    on_presend_ttl: 3 * 60 * 60 * 1000,
    mqs: [
        'RCV_MQ_BTC_4',
        'RCV_MQ_ETH_4',
        'RCV_MQ_ELOT_4',
        'RCV_MQ_EOS_4',
        'CFM_MQ_BTC_4',
        'CFM_MQ_ETH_4',
        'CFM_MQ_ELOT_4',
        'CFM_MQ_EOS_4',
        'InwalletMQ_BTC_4',
        'InwalletMQ_ETH_4',
        'InwalletMQ_ELOT_4',
        'InwalletMQ_EOS_4',
        'MatchOrderMQ',
        'ChangedInfoMQ',
        'MQ_SEND_BTC_4',
        'MQ_SEND_ETH_4',
        'MQ_SEND_ELOT_4',
        'MQ_SEND_EOS_4',
        'MQ_SEND_BTC_CFMS_4',
        'MQ_SEND_ETH_CFMS_4',
        'MQ_SEND_ELOT_CFMS_4',
        'MQ_SEND_EOS_CFMS_4',
        'MQ_SEND_GASTANKER_4',
        'MQ_SEND_CFM_MQ_GASTANKER_4',
        'MQ_PRESEND_4',
        'MQ_PRESEND_CONFIRM_4',
    ],
    receive_mq_btc: 'RCV_MQ_BTC_4',
    receive_mq_eth: 'RCV_MQ_ETH_4',
    receive_mq_elot: 'RCV_MQ_ELOT_4',
    receive_mq_eos: 'RCV_MQ_EOS_4',
    confirm_mq_btc: 'CFM_MQ_BTC_4',
    confirm_mq_eth: 'CFM_MQ_ETH_4',
    confirm_mq_elot: 'CFM_MQ_ELOT_4',
    confirm_mq_eos: 'CFM_MQ_EOS_4',
    inwallet_mq_btc: 'InwalletMQ_BTC_4',
    inwallet_mq_eth: 'InwalletMQ_ETH_4',
    inwallet_mq_elot: 'InwalletMQ_ELOT_4',
    inwallet_mq_eos: 'InwalletMQ_EOS_4',
    order_mq_match: 'MatchOrderMQ',
    change_mq_info: 'ChangedInfoMQ',
    send_mq_btc: 'MQ_SEND_BTC_4',
    send_mq_eth: 'MQ_SEND_ETH_4',
    send_mq_elot: 'MQ_SEND_ELOT_4',
    send_mq_eos: 'MQ_SEND_EOS_4',
    send_mq_btc_confirm: 'MQ_SEND_BTC_CFMS_4',
    send_mq_eth_confirm: 'MQ_SEND_ETH_CFMS_4',
    send_mq_elot_confirm: 'MQ_SEND_ELOT_CFMS_4',
    send_mq_eos_confirm: 'MQ_SEND_EOS_CFMS_4',
    send_from_gas_tanker: 'MQ_SEND_GASTANKER_4',
    send_from_gas_tanker_confirm: 'MQ_SEND_CFM_MQ_GASTANKER_4',
    presend_mq: 'MQ_PRESEND_4',
    presend_mq_confirm: 'MQ_PRESEND_CONFIRM_4',
    tokens: ['elot', 'eos'],
    order_mq_match_frq: 2
};